### ISSUE TITLE
Error when running command line 2

### ISSUE THREAD

**Issue by castte** [xaviripo/fmpd#6]
Hello! I´m trying your script but I get this error when running:
 
error: invalid utf-8 sequence of 1 bytes from index 6
    at https://raw.githubusercontent.com/xaviripo/fmpd/master/mod.ts:5:0

How can I solve it? Thanks for your help!

**Comment by xaviripo** [comment]
Hi! What operating system are you on? What version of deno are you using (`deno --version`)? What command are you running exactly?

**Comment by castte** [comment]
Windows 10;
deno 1.8.0 (release, x86_64-pc-windows-msvc)
v8 9.0.257.3
typescript 4.2.2
and the command is the one that you give: deno run --unstable --allow-net --allow-read --allow-write https://raw.githubusercontent.com/xaviripo/fmpd/master/mod.ts - < fbids.txt

**Comment by xaviripo** [comment]
I just tried that command with those same versions on Windows 10 and it works. Maybe try [downloading the repository](https://github.com/xaviripo/fmpd/archive/main.zip) and running the command agains the local copy of the `mod.ts` file instead of the online copy.

**Comment by castte** [comment]
Getting the same error, I don't know what could be causing it but thanks for your time

**Comment by xaviripo** [comment]
What terminal are you using? I've only tried Git Bash.

**Comment by castte** [comment]
Oh, I used cmd from Windows. I've installed Git Bash, tried on it,  and the command run seems to not exists. If you can explain the process with the terminal I would appreciate it. I'm situated in the folder with all the neccesary files and deno program.

**Comment by xaviripo** [comment]
> and the command run seems to not exists

The command you have to run starts with `deno`, not `run`. Make sure that Git Bash can find Deno by running `deno --version`, for example. If the version number shows up correctly, then you just have to run

```sh
deno run --unstable --allow-net --allow-read --allow-write https://raw.githubusercontent.com/xaviripo/fmpd/master/mod.ts - < fbids.txt
```

for the online version or, if that doesn't work,

```sh
deno run --unstable --allow-net --allow-read --allow-write mod.ts - < fbids.txt
```

for the local version.

**Comment by castte** [comment]
Same output here 
$ ./deno run --unstable --allow-net --allow-read --allow-write https://raw.githubusercontent.com/xaviripo/fmpd/master/mod.ts - < fbids.txt
error: invalid utf-8 sequence of 1 bytes from index 6
    at https://raw.githubusercontent.com/xaviripo/fmpd/master/mod.ts:4:0
Also with the local archives same error
It detects deno
$ ./deno --version
deno 1.8.0 (release, x86_64-pc-windows-msvc)
v8 9.0.257.3
typescript 4.2.2

**Comment by xaviripo** [comment]
I'm sorry, I'm not capable of reproducing the error. As this seems to be an error with how Deno processes the `mod.ts` file, you could try to report a bug at the [Deno repo](https://github.com/denoland/deno) and see if they have anything to see regarding this. If you find any other clue please report it here and I will try to look further into it.
