### ISSUE TITLE
Page Not Found

### ISSUE THREAD

**Issue by philphest** [xaviripo/fmpd#7]
I haven't been able to get the script to run correctly. If I try to go to the PREFIX+FBID URL directly in my browser, I have found that it gets directed to a Facebook PAGE NOT FOUND unless it's an image that has already been viewed in the browser session. 

Output from terminal (fbid obfuscated):
`Cannot fetch URL for picture with FBID ****************. Try accessing https://m.facebook.com/photo/view_full_size/?fbid=​​**************** in your browser and check if you can see the picture.`

**Comment by xaviripo** [comment]
That's very odd. I can see and download all pictures without problems.

How are you obtaining your FBIDs? Are you sure you have permission to see all those pictures?

**Comment by philphest** [comment]
I used this script to grab them:
`for (link of document.getElementsByTagName('a')) { if (!link.href.includes("?fbid=")) continue; console.log(new URL(link.href).searchParams.get("fbid")); }`

I'll do some more spot checking to make sure they are all FBIDs that I have access to and circle back.

**Comment by philphest** [comment]
Update: I downloaded the FBIDs again (same list of IDs) and a fresh cookies file and everything seems to be working fine. My guess is something was weird with the cookie info leading to issues with the downloads. Thanks for the attention!

**Comment by xaviripo** [comment]
It's a very unstable system, unfortunately. Glad that you managed to download the pics though 😃
